Fix the compile problem: RTjpeg.c:178: error: cast to union type from type not present in union RTjpeg.c:179: error: cast to union type from type not present in union RTjpeg.c:236: error: cast to union type from type not present in union RTjpeg.c:237: error: cast to union type from type not present in union RTjpeg.c:238: error: cast to union type from type not present in union RTjpeg.c:239: error: cast to union type from type not present in union RTjpeg.c:240: error: cast to union type from type not present in union RTjpeg.c: In function `RTjpeg_idct': RTjpeg.c:1200: error: cast to union type from type not present in union RTjpeg.c:1201: error: cast to union type from type not present in union RTjpeg.c:1202: error: cast to union type from type not present in union RTjpeg.c:1203: error: cast to union type from type not present in union RTjpeg.c:1204: error: cast to union type from type not present in union RTjpeg.c: In function `RTjpeg_set_intra': RTjpeg.c:2448: error: cast to union type from type not present in union RTjpeg.c:2449: error: cast to union type from type not present in union RTjpeg.c: In function `RTjpeg_bcomp': RTjpeg.c:2770: error: cast to union type from type not present in union
	Cause of the problem was using casts like (int64_t) when int64_t
	was NOT declared in the mmx_t union.