remove the RTJPEG mmx testing and messages.  As it turns out the MMX code will NOT build - seems no one has actually tried the "--enable-mmx" in a long time.  You get errors beginning with: RTjpeg.c: In function 'RTjpeg_set_intra': RTjpeg.c:2452: error: incompatible types in assignment RTjpeg.c:2453: error: incompatible types in assignment RTjpeg.c: In function 'RTjpeg_mcompressYUV420': RTjpeg.c:2845: warning: passing argument 3 of 'RTjpeg_bcomp' from incompatible pointer type
and continuing on.

The RTjpeg plugin should be declared "deprecated" so that it can be removed
in a future release.