HACK Alert!
OSX on Intel cpus needed to have -fno-pic when compiling the cpuinfo program -
to avoid the fatal error:
utils/cpuinfo.c:45: error: PIC register '%ebx' clobbered in 'asm'

Then when linking this would appear and the use of '-read_only_relocs suppress"
was needed.  This type of error seems to happen when inline assembly isn't
written properly on Mach-O based systems
/usr/bin/ld: /var/tmp//ccoyxrZt.o has external relocation entries in non-writable section (__TEXT,__text) for symbols:
_exit
_printf
_gettimeofday
_usleep