lqtplay.c:1518:36: warning: too many arguments in call to 'decode_audio'       decode_audio(AUDIO_BLOCK_SIZE);
decode_audio takes no arguments.   remove the argument so the error goes away.