Allow building of the mjpeg plugin even if libpng is not installed.   If libpng is not installed then <png.h> does not exist and this error results:
.deps/jpeg.Tpo -c jpeg.c  -fno-common -DPIC -o .libs/jpeg.o
     In file included from jpeg.h:4,
      from jpeg.c:7:
      libmjpeg.h:38:61: png.h: No such file or directory
      In file included from jpeg.h:4,
      from jpeg.c:7:
      libmjpeg.h:51: error: parse error before "jmp_buf"

What is  really needed in jpeg.c is <setjmp.h> so that 'struct jmpbuf' is
defined.  The fix is to change <png.h> to <setjmp.h>